config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants, only: [:index, :new, :create, :show] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  VALID_CATEGORIES = ['chinese', 'italian', 'japanese', 'french', 'belgian']
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, presence: true, inclusion: { in: VALID_CATEGORIES, message: "It is not a valid category" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render :new, status: :unprocessable_entity
    end
  end
  
    private

    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone_number, :category)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]
  def new
    @review = Review.new
  end
  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end
  private
  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
<h1>Articles</h1>
<ul class="list-groupe">
<% @restaurants.each do |restaurant| %>
<li class="list-group-item"><h2><%= restaurant.name %></h2>
<p><%= restaurant.address %></p>
<p><%= restaurant.phone_number %></p>
<p><%= restaurant.category %></p>
<%= link_to 'Show restaurant', restaurant_path(restaurant) %></li>
<% end %>
</ul>

<%= link_to 'New restaurant', new_restaurant_path(@restaurant) %>
<div>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= simple_form_for [@restaurant] do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :phone_number %>
<%= f.input :category %>
<%= f.submit "create", class: 'btn btn-primary' %>
<% end %>

app/views/restaurants/show.html.erb
<div class="container">
<h1>Details</h1>
<ul class="list-groupe">
<li class="list-group-item"><h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.category %></p></li>
</ul>
<ul class="list-groupe">
<% @restaurant.reviews.each do |review| %>
<li class="list-group-item"><p><%= review.rating %> / 10</p>
<p><%= review.content %></p></li>
<% end %>
</ul>
<div>

<%= link_to "Back to restaurants", restaurants_path %>
<%= link_to 'New review', new_restaurant_review_path(@restaurant) %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
<%= f.input :content %>
<%= f.input :rating %>
<%= f.submit "create", class: 'btn btn-primary' %>
<% end %>